//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESoft2App
{
    using System;
    using System.Collections.Generic;
    
    public partial class Complex
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Complex()
        {
            this.House = new HashSet<House>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int ConstructionStatusId { get; set; }
        public decimal PlusCost { get; set; }
        public decimal BuildingCost { get; set; }
        public int CityId { get; set; }
    
        public virtual City City { get; set; }
        public virtual ConstructionStatus ConstructionStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<House> House { get; set; }
    }
}
