//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESoft2App
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class eSoft2Entities : DbContext
    {
        public eSoft2Entities()
            : base("name=eSoft2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Apartment> Apartment { get; set; }
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<Complex> Complex { get; set; }
        public virtual DbSet<ConstructionStatus> ConstructionStatus { get; set; }
        public virtual DbSet<House> House { get; set; }
        public virtual DbSet<SellStatus> SellStatus { get; set; }
    }
}
